name: Frontend CI - Trigger Selenium Tests

on:
  push:
    branches:
      - develop  

jobs:
  trigger_tests:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Selenium Tests
        run: |
          curl -X POST -H "Authorization: token ${{ secrets.ACCESS_PORTAL_FE_REPO }}" \
               -H "Accept: application/vnd.github.v3+json" \
               https://api.github.com/repos/flicfinancial/Flic-testing-next/dispatches \
               -d '{"event_type": "frontend-updated", "client_payload": {"ref": "develop"}}'
